//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package view;

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.ListView;
import android.widget.SimpleAdapter;
import br.com.pierry.w2h.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class PrincipalActivity_
    extends PrincipalActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_principal);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        lvAtiv = ((ListView) findViewById(br.com.pierry.w2h.R.id.lvAtiv));
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(br.com.pierry.w2h.R.id.lvAtiv));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        lvAtivItemClicked(position);
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(br.com.pierry.w2h.R.id.lvAtiv));
            if (view!= null) {
                view.setOnItemLongClickListener(new OnItemLongClickListener() {


                    @Override
                    public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                        lvAtivLongItemClicked(position);
                        return true;
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static PrincipalActivity_.IntentBuilder_ intent(Context context) {
        return new PrincipalActivity_.IntentBuilder_(context);
    }

    @Override
    public void setAdapterList(final SimpleAdapter adapter) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    PrincipalActivity_.super.setAdapterList(adapter);
                } catch (RuntimeException e) {
                    Log.e("PrincipalActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getListView(final ProgressDialog dialog) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    PrincipalActivity_.super.getListView(dialog);
                } catch (RuntimeException e) {
                    Log.e("PrincipalActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PrincipalActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PrincipalActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
