//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package view;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import br.com.pierry.w2h.R.id;
import br.com.pierry.w2h.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class ReadActivity_
    extends ReadActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_read);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        tvHowMuchTexto = ((TextView) findViewById(id.tvHowMuchTexto));
        tvHowMuch = ((TextView) findViewById(id.tvHowMuch));
        tvWhoTexto = ((TextView) findViewById(id.tvWhoTexto));
        tvWhat = ((TextView) findViewById(id.tvWhat));
        tvWhatTexto = ((TextView) findViewById(id.tvWhatTexto));
        tvWhere = ((TextView) findViewById(id.tvWhere));
        tvWho = ((TextView) findViewById(id.tvWho));
        tvWhyTexto = ((TextView) findViewById(id.tvWhyTexto));
        tvWhy = ((TextView) findViewById(id.tvWhy));
        tvHowTexto = ((TextView) findViewById(id.tvHowTexto));
        tvWhereTexto = ((TextView) findViewById(id.tvWhereTexto));
        tvWhen = ((TextView) findViewById(id.tvWhen));
        tvWhenTexto = ((TextView) findViewById(id.tvWhenTexto));
        tvHow = ((TextView) findViewById(id.tvHow));
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ReadActivity_.IntentBuilder_ intent(Context context) {
        return new ReadActivity_.IntentBuilder_(context);
    }

    @Override
    public void alterarFontes() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ReadActivity_.super.alterarFontes();
                } catch (RuntimeException e) {
                    Log.e("ReadActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void iniciarTextos(final String what, final String why, final String where, final String when, final String who, final String how, final String howmuch) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ReadActivity_.super.iniciarTextos(what, why, where, when, who, how, howmuch);
                } catch (RuntimeException e) {
                    Log.e("ReadActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ReadActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ReadActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
